# Generated by Django 6.0.2 on 2026-04-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_options_alter_itempedido_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='entregue',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('producao', 'Em Produção'), ('entregue', 'Entregue')], default='pendente', max_length=10),
        ),
    ]
