# Generated by Django 6.0.2 on 2026-04-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_entregue_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
